name: biometryd
version: 0.0.1
summary: biometryd mediates/multiplexes to biometric devices
description: biometryd mediates/multiplexes access to biometric devices
  biometryd mediates and multiplexes access to biometric devices present
  on the system enabling applications and system components to
  leverage them for identification and verification of users.

apps:
  biometryd:
    daemon: simple
    command: bin/biometryd run
  cli:
    command: bin/biometryd

parts:
  biometryd:
    plugin: cmake
    configflags:
      - -DCMAKE_VERBOSE_MAKEFILE=ON
    source: .
    build-packages:
      - cmake
      - doxygen
      - google-mock
      - graphviz
      - libapparmor-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-test-dev
      - libdbus-cpp-dev
      - libdbus-1-dev
      - libelf-dev
      - libgtest-dev
      - libprocess-cpp-dev
      - libsqlite3-dev
      - lsb-release
      - pkg-config
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtdeclarative5-test-plugin
    snap:
      - bin/biometryd
      - etc/dbus-1/system.d
      - lib/
      - lib/libbiometryd*
